### ISSUE TITLE
Dark mode for edge sidebar

### ISSUE THREAD

**Issue by axlpascual** [jerry1100/messenger-dark-theme#22]
Current version doesn't work with messenger.com for edge sidebar

**Comment by jerry1100** [comment]
@axlpascual mind posting a screenshot? Not sure what you mean.

**Comment by OwlPrince** [comment]
He means the sidebar on the right side of Edge, Messenger can be embedded there as an "app", which uses messenger.com.

Your dark theme works wonderfully when messenger.com is opened on a simple tab, but on the sidebar it stays in light mode.

Edge's "force dark mode" seems to be a solution to this, but it changes every site opened, destroying some of them in the process.

It would be greatly appreciated if your dark theme would apply on the sidebar as well.

**Comment by vincearnold** [comment]
Hey @jerry1100,
Here is a screenshot of the Edge Sidebar messenger app:
![image](https://user-images.githubusercontent.com/97923337/217955434-fd8da6ad-08f0-4d0c-906e-8d27e3740023.png)

**Comment by jerry1100** [comment]
Thanks for the explanation. Unfortunately this doesn't seem possible at the moment since extensions don't work in the sidebar.

See:
1. https://techcommunity.microsoft.com/t5/discussions/edge-bar-bar-doesn-t-support-extensions-other-improvements/m-p/3432863
2. https://www.reddit.com/r/MicrosoftEdge/comments/z8n6ml/comment/iydof8t/?utm_source=share&utm_medium=web2x&context=3
