### ISSUE TITLE
White background of incoming chat bubbles

### ISSUE THREAD

**Issue by Rymka69** [jerry1100/messenger-dark-theme#31]
![image](https://github.com/jerry1100/messenger-dark-theme/assets/91845700/d3ec7c9c-a429-4fb1-9971-87596c69732e)
This started like a few days ago, and no matter what theme the chat has.

I'm using Edge, so maybe that's why this bug occurs, but I have been using this extension for a long time and it's the first time seeing this.

**Comment by jerry1100** [comment]
Hi, this has been fixed on the chrome web store. I also submitted the fix on the Microsoft store but they take a lot longer to approve.

In the meantime, here’s how to install chrome extensions on edge: https://support.microsoft.com/en-us/microsoft-edge/add-turn-off-or-remove-extensions-in-microsoft-edge-9c0ec68c-2fbc-2f2c-9ff0-bdc76f46b026#:~:text=Add%20an%20extension%20to%20Microsoft%20Edge%20from%20the%20Chrome%20Web,then%20select%20Allow%20to%20confirm.

Going to close since it should be resolved but feel free to reopen if you need more help.
