### ISSUE TITLE
Recipient text is white on white in Edge

### ISSUE THREAD

**Issue by petrathomas** [jerry1100/messenger-dark-theme#33]
Using Edge with v1.7, changes at the Meta end have made the recipient text turn white on a white text block. It is unreadable. Sender text is fine. Used to work perfectly.

**Comment by Bullsized** [comment]
Can confirm this:
![image](https://github.com/jerry1100/messenger-dark-theme/assets/26943431/63ded2bb-b39e-4220-81a2-420784388ff5)
![image](https://github.com/jerry1100/messenger-dark-theme/assets/26943431/ee09c1c0-4c01-4c44-83c2-687cf303b469)

It's been happening since the end of last week (2023-10-26).

Here's my Dark Theme version:
![image](https://github.com/jerry1100/messenger-dark-theme/assets/26943431/d46a493a-b8af-4df3-b422-fb0b63bbf529)

Here's my Edge version:
![image](https://github.com/jerry1100/messenger-dark-theme/assets/26943431/88b00f61-ce38-4dc3-a0a1-fd118119c74a)

**Comment by Bullsized** [comment]
It's this one:
![image](https://github.com/jerry1100/messenger-dark-theme/assets/26943431/b68a1299-3593-4a45-8353-696fb139bf00)
![image](https://github.com/jerry1100/messenger-dark-theme/assets/26943431/c661b5f9-6ff9-4b86-a27d-9ee1a8ba3964)

**Comment by petrathomas** [comment]
Hello Jerry,

Yes, this looks like it. Thanks for the quick response !

Cheers,
Petra
________________________________

**Comment by jerry1100** [comment]
Hi, this has been fixed. I submitted a new version (1.8) on the edge store but Microsoft just takes long to approve it.

See https://github.com/jerry1100/messenger-dark-theme/issues/31#issuecomment-1782510633 for how to get it on edge.

**Comment by Bullsized** [comment]
@jerry1100 thanks for the quick reaction!
